name: Integration

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  python:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.7, 3.8, 3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Ubuntu packages
      run: |
        sudo -H ./utils/project.sh install packages
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Install Python dependencies
      run: |
        make V=1 install
    - name: Run tests
      run: make V=1 ci.test

  documentation:
    name: Documentation
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install Ubuntu packages
      run: |
        sudo -H ./utils/project.sh install buildhost
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Build documentation
      run: |
        make V=1 docs.clean docs.html
    - name: Deploy
      if:  github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ github.token }}
        BRANCH: gh-pages
        FOLDER: dist/docs
        CLEAN: true # Automatically remove deleted files from the deploy branch
        SINGLE_COMMIT: True
        COMMIT_MESSAGE: build from commit ${{ github.sha }}
